{{- if .Values.cantaloupe.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.cantaloupe.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cantaloupe.service.type }}
  ports:
    - port: {{ .Values.cantaloupe.service.port }}
      targetPort: 8182
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.cantaloupe.selectorLabels" . | nindent 4 }}
{{- end }}